#!/bin/bash
apt-get update
puppet resource package git ensure=present

puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running

puppet resource file /tmp/3133276f/research ensure=absent force=true
puppet resource file /tmp/3133276f/research ensure=directory


cd /tmp/3133276f/research/
git clone https://github.com/Thariq-git/3133276f_op_repo.git
cp -p /tmp/3133276f/research/3133276f_index.html /var/www/html/index.html
